require("custom.term")
require("custom.remap")
require("custom.harpoon")
require("custom.fugitive")
require("custom.undotree")
require("custom.netrw")
require("custom.everforest")
require("custom.set")
